export const questions = [
  {
    id: 0,
    desc: "歡迎來到獵人念能力測試",
    multiAns: false,
  },
  {
    id: 1,
    desc: "有一天你走在路上看到兩隻被拋棄的黑貓，你會怎麼做？",
    multiAns: false,
  },
  {
    id: 2,
    desc: "帶回家之後怎麼辦呢？",
    multiAns: false,
  },
  {
    id: 2002,
    desc: "為什麼不帶回家呢？",
    multiAns: false,
  },
  {
    id: 3,
    desc: "早上起床後發現天空烏雲密布，聽天氣預報說降雨概率為40%。你出門會帶傘嗎？",
    multiAns: false,
  },
  {
    id: 4,
    desc: "和朋友約好出去玩，可是約定時間到了朋友卻沒有來。你能等多少分鐘？",
    multiAns: false,
  },
  {
    id: 5,
    desc: "這次是你遲到了。對方生氣了，你會怎麼做？",
    multiAns: false,
  },
  {
    id: 6,
    desc: "早上醒來你發現自己變成動物了。是什麼動物？",
    multiAns: false,
  },
  {
    id: 7,
    desc: "承Q6，為什麼這麼想？",
    multiAns: false,
  },
  {
    id: 8,
    desc: "你最擅長的是？",
    multiAns: false,
  },
  {
    id: 9,
    desc: "你最討厭的是？",
    multiAns: false,
  },
  {
    id: 10,
    desc: "如果你成為了盜賊，第一件想偷的是什麼？",
    multiAns: false,
  },
  {
    id: 11,
    desc: "你覺得自己的優點有？",
    multiAns: true,
  },
  {
    id: 12,
    desc: "覺得自己的缺點有？",
    multiAns: true,
  },
  {
    id: 13,
    desc: "什麼樣的人會讓你真的起殺心？",
    multiAns: true,
  },
  {
    id: 14,
    desc: "什麼時候你會哭？",
    multiAns: true,
  },
  {
    id: 15,
    desc: "覺得魔術師很厲害嗎？",
    multiAns: false,
  },
  {
    id: 16,
    desc: "用行動力逮捕犯人的警察是不對的嗎？",
    multiAns: false,
  },
  {
    id: 17,
    desc: "書架上的書順序排得亂七八糟的話會不舒服嗎？",
    multiAns: false,
  },
  {
    id: 18,
    desc: "絕對不會花心嗎？"
  },
  {
    id: 19,
    desc: "只要自己好的話其他怎樣都無所謂嗎？",
    multiAns: false,
  },
  {
    id: 20,
    desc: "不喜歡整理收拾嗎？",
    multiAns: false,
  },
];

const answers = [
  {
    label: "",
    desc: "開始答題",
    questionID: 0,
    score: setScore(0,0,0,0,0,0),
  },
  {
    label: "A",
    desc: "帶回家",
    questionID: 1,
    score: setScore(10,0,0,0,10,10),
  },
  {
    label: "B",
    desc: "不帶回家",
    questionID: 1,
    score: setScore(0,10,10,10,0,0),
  },
  {
    label: "A",
    desc: "不管怎樣都一定要養！",
    questionID: 2,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "B",
    desc: "想養，但家人會反對於是去找別人養",
    questionID: 2,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "C",
    desc: "不想養，找別人養",
    questionID: 2,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "D",
    desc: "以上皆非",
    questionID: 2,
    score: setScore(0,0,0,0,0,0),
  },
  {
    label: "A",
    desc: "因為家裡不給養",
    questionID: 2002,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "B",
    desc: "因為黑貓不吉利",
    questionID: 2002,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "C",
    desc: "儘管現在是很可愛，總有一天會厭煩的",
    questionID: 2002,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "D",
    desc: "以上皆非",
    questionID: 2002,
    score: setScore(0,0,0,0,0,0),
  },
  {
    label: "A",
    desc: "覺得肯定會下雨於是帶上手頭的傘",
    questionID: 3,
    score: setScore(0,0,15,0,15,0),
  },
  {
    label: "B",
    desc: "覺得大概會下雨就帶了折疊傘",
    questionID: 3,
    score: setScore(0,0,0,15,0,15),
  },
  {
    label: "C",
    desc: "不帶傘",
    questionID: 3,
    score: setScore(15,15,0,0,0,0),
  },
  {
    label: "A",
    desc: "等不了",
    questionID: 4,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "B",
    desc: "5分鐘左右",
    questionID: 4,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "C",
    desc: "10分鐘左右",
    questionID: 4,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "D",
    desc: "15分鐘左右",
    questionID: 4,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "E",
    desc: "20分鐘左右",
    questionID: 4,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "F",
    desc: "可以一直等下去",
    questionID: 4,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "A",
    desc: "道歉，3天內為對方做任何事",
    questionID: 5,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "B",
    desc: "道歉，讓對方心情好起來",
    questionID: 5,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "C",
    desc: "道歉，下次起早來20分鐘",
    questionID: 5,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "D",
    desc: "辯解，不認錯",
    questionID: 5,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "E",
    desc: "辯解，讓對方心情好起來",
    questionID: 5,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "F",
    desc: "這種事不可能發生",
    questionID: 5,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "A",
    desc: "綿羊",
    questionID: 6,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "B",
    desc: "黑豹",
    questionID: 6,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "C",
    desc: "猴子",
    questionID: 6,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "D",
    desc: "老虎",
    questionID: 6,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "E",
    desc: "狼",
    questionID: 6,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "F",
    desc: "珀伽索斯（希臘神話中的飛馬）",
    questionID: 6,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "G",
    desc: "獅子",
    questionID: 6,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "A",
    desc: "因為動物占卜裡自己測出來是它",
    questionID: 7,
    score: setScore(0,0,15,0,15,0),
  },
  {
    label: "B",
    desc: "因為喜歡這種動物",
    questionID: 7,
    score: setScore(15,0,0,0,0,15),
  },
  {
    label: "C",
    desc: "因為想變成這種動物",
    questionID: 7,
    score: setScore(0,15,0,15,0,0),
  },
  {
    label: "D",
    desc: "不為什麼",
    questionID: 7,
    score: setScore(5,5,5,5,5,5),
  },
  {
    label: "A",
    desc: "數理",
    questionID: 8,
    score: setScore(0,0,35,0,0,0),
  },
  {
    label: "B",
    desc: "語文",
    questionID: 8,
    score: setScore(0,0,0,0,35,0),
  },
  {
    label: "C",
    desc: "社會",
    questionID: 8,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "D",
    desc: "創作",
    questionID: 8,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "E",
    desc: "體育",
    questionID: 8,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "F",
    desc: "無",
    questionID: 8,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "A",
    desc: "數理",
    questionID: 9,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "B",
    desc: "語文",
    questionID: 9,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "C",
    desc: "社會",
    questionID: 9,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "D",
    desc: "創作",
    questionID: 9,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "E",
    desc: "體育",
    questionID: 9,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "F",
    desc: "無",
    questionID: 9,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "A",
    desc: "人命",
    questionID: 10,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "B",
    desc: "錢",
    questionID: 10,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "C",
    desc: "鑽石、寶石",
    questionID: 10,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "D",
    desc: "美術品",
    questionID: 10,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "E",
    desc: "古書",
    questionID: 10,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "F",
    desc: "絕對不會成為盜賊",
    questionID: 10,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "A",
    desc: "規規矩矩",
    questionID: 11,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "B",
    desc: "有責任感",
    questionID: 11,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "C",
    desc: "被人信賴",
    questionID: 11,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "D",
    desc: "有引人注目的特長",
    questionID: 11,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "E",
    desc: "對自己要求嚴格",
    questionID: 11,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "F",
    desc: "有行動力",
    questionID: 11,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "G",
    desc: "朋友多",
    questionID: 11,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "H",
    desc: "反复無常難以捉摸",
    questionID: 11,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "I",
    desc: "畫畫唱歌很好",
    questionID: 11,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "J",
    desc: "利己主義",
    questionID: 11,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "K",
    desc: "擅長精細活",
    questionID: 11,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "L",
    desc: "我行我素",
    questionID: 11,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "A",
    desc: "沒有協調性",
    questionID: 12,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "B",
    desc: "粗心大意",
    questionID: 12,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "C",
    desc: "愛說謊",
    questionID: 12,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "D",
    desc: "討厭的人有10個以上",
    questionID: 12,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "E",
    desc: "對錢斤斤計較",
    questionID: 12,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "F",
    desc: "覺得沒道理的事就無法接受",
    questionID: 12,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "G",
    desc: "自我中心",
    questionID: 12,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "H",
    desc: "為達到目的不擇手段",
    questionID: 12,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "I",
    desc: "容易生氣",
    questionID: 12,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "J",
    desc: "淚點低",
    questionID: 12,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "K",
    desc: "行動遲緩",
    questionID: 12,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "L",
    desc: "容易上當",
    questionID: 12,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "A",
    desc: "殺了自己家人的人",
    questionID: 13,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "B",
    desc: "殺了自己喜歡的人的人",
    questionID: 13,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "C",
    desc: "給了自己最大屈辱的人",
    questionID: 13,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "D",
    desc: "想殺自己的人",
    questionID: 13,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "E",
    desc: "在自己面前大量濫殺無辜的人",
    questionID: 13,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "F",
    desc: "背叛自己的人",
    questionID: 13,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "A",
    desc: "重要的人死去時",
    questionID: 14,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "B",
    desc: "悲傷或是感動時",
    questionID: 14,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "C",
    desc: "被甩時",
    questionID: 14,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "D",
    desc: "被求婚時",
    questionID: 14,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "E",
    desc: "看體育項目感動時",
    questionID: 14,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "F",
    desc: "達成某重大目標時",
    questionID: 14,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "G",
    desc: "工作出現大失敗時",
    questionID: 14,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "H",
    desc: "身邊長時間沒人時",
    questionID: 14,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "I",
    desc: "回憶痛苦往事時",
    questionID: 14,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "J",
    desc: "自尊被傷害時",
    questionID: 14,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "K",
    desc: "被朋友背叛",
    questionID: 14,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "L",
    desc: "不大哭",
    questionID: 14,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "",
    desc: "是",
    questionID: 15,
    score: setScore(0,30,0,0,0,0),
  },
  {
    label: "",
    desc: "否",
    questionID: 15,
    score: setScore(6,0,6,6,6,6),
  },
  {
    label: "",
    desc: "是",
    questionID: 16,
    score: setScore(0,0,0,0,30,0),
  },
  {
    label: "",
    desc: "否",
    questionID: 16,
    score: setScore(6,6,6,6,0,6),
  },
  {
    label: "",
    desc: "是",
    questionID: 17,
    score: setScore(0,0,30,0,0,0),
  },
  {
    label: "",
    desc: "否",
    questionID: 17,
    score: setScore(6,6,0,6,6,6),
  },
  {
    label: "",
    desc: "是",
    questionID: 18,
    score: setScore(30,0,0,0,0,0),
  },
  {
    label: "",
    desc: "否",
    questionID: 18,
    score: setScore(0,6,6,6,6,6),
  },
  {
    label: "",
    desc: "是",
    questionID: 19,
    score: setScore(0,0,0,30,0,0),
  },
  {
    label: "",
    desc: "否",
    questionID: 19,
    score: setScore(6,6,6,0,6,6),
  },
  {
    label: "",
    desc: "是",
    questionID: 20,
    score: setScore(0,0,0,0,0,30),
  },
  {
    label: "",
    desc: "否",
    questionID: 20,
    score: setScore(6,6,6,6,6,0),
  },
];

const serializedAnswers = answers.map((ans, idx) => ({id: idx, ...ans}));

export {serializedAnswers as answers};

export function setScore(enhancer,transmuter,conjurer,specialist,manipulator,emitter) {
  return {
    enhancer,
    transmuter,
    conjurer,
    specialist,
    manipulator,
    emitter,
  };
}
